name: CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  lean:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build: false
          lint: false
          test: false
      - run: make install
      - run: make all
